name: proyectouedadas
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  cloud_firestore: ^1.0.6
  firebase_auth:
  google_sign_in:
  google_fonts:
  font_awesome_flutter:
  cupertino_icons: ^1.0.2
  material_floating_search_bar:



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/